canal/urls.py
from django.urls import path
from . import views

app_name = 'canal'

urlpatterns = [
    path('', views.home, name='home'),
    path('sorter_in/', views.sorter_in, name='sorter_in'),
    path('can_trace_info/', views.can_trace_info, name='can_trace_info'),
    path('can_trace_plot/', views.can_trace_plot, name='can_trace_plot'),
    path('can_trace_bitwise/', views.can_trace_bitwise, name='can_trace_bitwise'),

]

settings/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('canal.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

canal/models.py
from django.db import models

# Create your models here.

canal/views.py
import os
from django.conf import settings

from django.shortcuts import render
from .functions import dbc_sorter, get_asc_info, get_plots, get_plots_bitwise
from django.http import HttpResponse


def home(request):
    return render(request, 'canal/home.html')


def sorter_in(request):
    if request.method == 'GET':
        return render(request, 'canal/sorter_in.html')
    if request.method == 'POST':
        uploaded_dbc_file = request.FILES['dbcfile']
        filepath = dbc_sorter(uploaded_dbc_file)
        if os.path.exists(filepath):
            with open(filepath, 'rb') as fh:
                response = HttpResponse(fh.read(), content_type="application/txt")
                response['Content-Disposition'] = 'inline; filename=' + os.path.basename(filepath)
                return response
        return render(request, 'canal/sorter_in.html')


def can_trace_info(request):
    if request.method == 'GET':
        return render(request, 'canal/can_trace_info.html')
    if request.method == 'POST':
        uploaded_asc_file = request.FILES['ascfile']
        ch1, ch2 = get_asc_info(uploaded_asc_file)
        return render(request, 'canal/can_trace_info.html', {'ch1': ch1, 'ch2': ch2})


def can_trace_plot(request):
    if request.method == 'GET':
        return render(request, 'canal/can_trace_plot.html')
    if request.method == 'POST':
        uploaded_asc_file = request.FILES['ascfile']
        message_id = request.POST['message_id']
        scripts, divs = get_plots(uploaded_asc_file, message_id)
        context = {'scripts': scripts,
                   'divs': divs,}
        return render(request, 'canal/can_trace_plot.html', context)


def can_trace_bitwise(request):
    if request.method == 'GET':
        return render(request, 'canal/can_trace_bitwise.html')
    if request.method == 'POST':
        uploaded_asc_file = request.FILES['ascfile']
        message_id = request.POST['message_id']
        instructions = request.POST['instructions']
        # scripts, divs = get_plots_bitwise(uploaded_asc_file, message_id)
        scripts, divs, data_changes = get_plots_bitwise(uploaded_asc_file, message_id, instructions)
        context = {'scripts': scripts,
                   'divs': divs,
                   'data_changes': data_changes}
        return render(request, 'canal/can_trace_bitwise.html', context)

canal/templates/canal/base.html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
  <meta name="generator" content="Hugo 0.80.0">
  <title>Canal</title>
  <!-- Bootstrap core CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">

  <style>
  .bd-placeholder-img {
  font-size: 1.125rem;
  text-anchor: middle;
  -webkit-user-select: none;
  -moz-user-select: none;
  user-select: none;
  }

  @media (min-width: 768px) {
    .bd-placeholder-img-lg {
    font-size: 3.5rem;
    }
  }
  </style>
</head>


<body>

<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'canal:home' %}">CANAL</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
      <ul class="navbar-nav me-auto mb-2 mb-md-0">
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'canal:sorter_in' %}">dbc-Sorter</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{%  url 'canal:can_trace_info' %}">CanTraceInfo</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{%  url 'canal:can_trace_plot' %}">CanTraceBytes</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{%  url 'canal:can_trace_bitwise' %}">CanTraceBits</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-bs-toggle="dropdown" aria-expanded="false">Future tools</a>
          <ul class="dropdown-menu" aria-labelledby="dropdown01">
            <li><a class="dropdown-item" href="#">Tool 1</a></li>
            <li><a class="dropdown-item" href="#">Tool 2</a></li>
            <li><a class="dropdown-item" href="#">Tool 3</a></li>
          </ul>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>


{% block content %}
{% endblock content %}


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
<script src="https://cdn.bokeh.org/bokeh/release/bokeh-2.3.0.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.bokeh.org/bokeh/release/bokeh-widgets-2.3.0.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.bokeh.org/bokeh/release/bokeh-tables-2.3.0.min.js" crossorigin="anonymous"></script>


</body>
</html>

canal/templates/canal/can_trace_bitwise.html
{% extends 'canal/base.html' %}

{% block content %}
<main class="container">
    <div class="starter-template text-center py-5 px-3">
        <br>
        <h1>Can Trace Plot Bits</h1>
        <p>This will plot whatever bits and bit ranges that you specify</p>
        <p>from the desired CAN message in the file that you upload</p>
        <br>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}

            <p>Please enter the Hex ID of the CAN message, without the 0x. </p>
            <p>For example, for 0x40a, enter 40a or 40A</p>
            Message ID <input type="text" name="message_id">
            <br><br><br>
            <p>Please enter the bits and bit ranges you would like to plot</p>
            <p>Example: To plot bits 1, 2, and bit ranges 3-12, and 13-17, please enter:</p>
            <p>1, 2, 3-12, 13-17</p>
            Bits and bit ranges <input type="text" name="instructions">
            <br><br><br>
            <p>Please select and upload a file</p>
            <input type="file" name="ascfile" accept=".asc">
            <button type="submit"> Upload File</button>
        </form>
    </div>

    {% if data_changes %}
    <p>Message data has varying byte length. This may produce strange results. </p>
    {% endif %}
    {% for div in divs %}
        <div class="text-center">{{ div | safe }}</div>
    {% endfor %}
</main>

{% for script in scripts %}
{{ script | safe }}
{% endfor %}

{% endblock content %}

canal/templates/canal/can_trace_chooser.html
{% extends 'canal/base.html' %}




{% block content %}
<main class="container">
    <div class="starter-template text-center py-5 px-3">
        <br>
        <h1>Can Trace Visualizer</h1>
        <p>Let's see some can traces!!!</p>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <input type="file" name="ascfile" accept=".asc">
            <button type="submit"> Upload File</button>
        </form>
    </div>

<div>{{ div | safe }}</div>

</main>

{{ script | safe }}

test

{% endblock content %}

canal/templates/canal/can_trace_in.html
{% extends 'canal/base.html' %}




{% block content %}
<main class="container">
    <div class="starter-template text-center py-5 px-3">
        <br>
        <h1>Can Trace Visualizer</h1>
        <p>Let's see some can traces!!!</p>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <input type="file" name="ascfile" accept=".asc">
            <button type="submit"> Upload File</button>
        </form>
    </div>

<div>{{ div | safe }}</div>

</main>

{{ script | safe }}

test

{% endblock content %}

canal/templates/canal/can_trace_info.html
{% extends 'canal/base.html' %}

{% block content %}
<main class="container">
    <div class="starter-template text-center py-5 px-3">
        <br>
        <h1>Can Trace Info</h1>
        <p>This will give you information about the CAN Trace file</p>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <input type="file" name="ascfile" accept=".asc">
            <button type="submit"> Upload File</button>
        </form>
    </div>

    <div>
        <h3>Messages on Channel 1 </h3>
        <table class="table table-sm table-hover">
            <thead>
                <tr>
                    <th scope="col">Hex ID</th>
                    <th scope="col">Data Length (bytes)</th>
                </tr>
            </thead>
            <tbody>
                {% for key, value in ch1 %}
                <tr>
                    <td>{{key}}</td>
                    <td>{{value}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>

                <h3>Messages on Channel 2 </h3>
        <table class="table table-sm table-hover">
            <thead>
                <tr>
                    <th scope="col">Hex ID</th>
                    <th scope="col">Data Length (bytes)</th>
                </tr>
            </thead>
            <tbody>
                {% for key, value in ch2 %}
                <tr>
                    <td>{{key}}</td>
                    <td>{{value}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</main>



{% endblock content %}

canal/templates/canal/can_trace_plot.html
{% extends 'canal/base.html' %}

{% block content %}
<main class="container">
    <div class="starter-template text-center py-5 px-3">
        <br>
        <h1>Can Trace Plot Bytes</h1>
        <p>This will plot the bytes of the specified CAN message</p>
        <p>from the file that you upload</p>
        <br>

        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <p>Please enter the Hex ID of the CAN message, without the 0x. </p>
            <p>For example, for 0x40a, enter 40a or 40A</p>
            Message ID
            <input type="text" name="message_id"><br>
            <input type="file" name="ascfile" accept=".asc">
            <button type="submit"> Upload File</button>
        </form>
    </div>




{% for div in divs %}
<div class="text-center">{{ div | safe }}</div>
{% endfor %}

</main>



{% for script in scripts %}
{{ script | safe }}
{% endfor %}


{% endblock content %}

canal/templates/canal/cantrace_in.html
{% extends 'canal/base.html' %}




{% block content %}
<main class="container">
    <div class="starter-template text-center py-5 px-3">
        <br>
        <h1>Can Trace Visualizer</h1>
        <p>Let's see some can traces!!!</p>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <input type="file" name="ascfile" accept=".asc">
            <button type="submit"> Upload File</button>
        </form>
    </div>

<div>{{ div | safe }}</div>

</main>

{{ script | safe }}

test

{% endblock content %}

canal/templates/canal/home.html
{% extends 'canal/base.html' %}

{% block content %}

<main class="container">

  <div class="starter-template text-center py-5 px-3">
    <br>
      <h1>By-Wire Script Collections</h1>
      <p class="lead">Welcome to our collection of helpful scripts. </p>
      <p>Half baked scripts are welcome</p>
  </div>

</main>

{% endblock content %}

canal/templates/canal/sorter_in.html
{% extends 'canal/base.html' %}



{% block content %}
<main class="container">

  <div class="starter-template text-center py-5 px-3">
    <br>
      <h1>DBC Sorter</h1>
      <p>
          DBC Sorter was written to keep changes on pacmod <br>
          dbc files from accidentally wreaking havoc on <br>
          Pi-Innovo Simulink models.
      </p>
      <p>
          DBC sorter will take any dbc file and sort the signals <br>
          inside the messages based on byte position.
      </p>
      <p>
          This keeps the signals in the correct order when used <br>
          inside a Pi-Innovo CAN-Read block.
      </p>
      <p>
          Failure to keep the signals in order will result in signals <br>
          getting switched inside the simulink model.
      </p>



      <form method="post" enctype="multipart/form-data">
          {% csrf_token %}
          <input type="file" name="dbcfile" accept=".dbc">
          <button type="submit"> Upload File</button>
</form>

  </div>



</main>

{% endblock content %}